<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Watchtower.Entities\Watchtower.Entities.csproj" />
    <ProjectReference Include="..\Watchtower.Ingestion\Watchtower.Ingestion.csproj" />
    <ProjectReference Include="..\Watchtower.Detection\Watchtower.Detection.csproj" />
    <ProjectReference Include="..\Watchtower.Repository\Watchtower.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.*" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.*" />
    <PackageReference Include="QuestPDF" Version="2024.*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
